# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = match:class .*, suppress_event maximize

# Force chromium into a tile to deal with --app bug
windowrule = match:class ^(Chromium)$, tile on

# Float sound and bluetooth settings
windowrule = match:class ^(org.pulseaudio.pavucontrol|blueberry.py)$, float on

# Float Steam, fullscreen RetroArch
windowrule = match:class ^(steam)$, float on
windowrule = match:class ^(com.libretro.RetroArch)$, fullscreen on

# Just dash of opacity
windowrule = match:class .*, opacity 1 0.97
windowrule = match:initial_title ^(youtube.com_/)$, opacity 1 1 # Youtube
windowrule = match:class ^(zoom|vlc|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta)$, opacity 1 1
windowrule = match:class ^(com.libretro.RetroArch|steam)$, opacity 1 1

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

# Proper background blur for wofi
layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha on, match:namespace wofi

# Float in the middle for clipse clipboard manager
windowrule = match:class (clipse), float on
windowrule = match:class (clipse), size 622 652
windowrule = match:class (clipse), stay_focused on

# Autostart Ghostty in fullscreen on workspace 10
windowrule = match:class ^(com.mitchellh.ghostty)$, match:workspace 10, fullscreen on
